// DATOS WBS TM01 - GENERADOS AUTOMATICAMENTE
// Archivo: datos_wbs_TM01_items.js
// Fecha: 2025-10-24 12:34:09
// Total items: 59

window.wbsDataGlobal = window.datos_wbs = {
    "fecha_actualizacion": "2025-10-24",
    "total_items": 59,
    "version": "2.1",
    "items": [
    {
        "item":  "1",
        "descripcion":  "SISTEMA SOS",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "SOS",
        "totalCOP":  "",
        "tipo":  "capitulo",
        "total":  ""
    },
    {
        "item":  "1.1",
        "descripcion":  "SUMINISTROS SOS",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "SOS",
        "totalCOP":  "",
        "tipo":  "subcapitulo",
        "total":  ""
    },
    {
        "item":  "1.1.1",
        "descripcion":  "Poste metálico galvanizado 4m",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "3,520,000",
        "criterio":  "Estructura principal",
        "unidad":  "UND",
        "vu":  "800",
        "sistema":  "SOS",
        "totalCOP":  "306,240,000",
        "tipo":  "item",
        "total":  "69,600"
    },
    {
        "item":  "1.1.2",
        "descripcion":  "Gabinete control IP65",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "2,640,000",
        "criterio":  "Protección equipos",
        "unidad":  "UND",
        "vu":  "600",
        "sistema":  "SOS",
        "totalCOP":  "229,680,000",
        "tipo":  "item",
        "total":  "52,200"
    },
    {
        "item":  "1.1.3",
        "descripcion":  "Teléfono resistente vandalismo",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Comunicación VoIP",
        "unidad":  "UND",
        "vu":  "1,500",
        "sistema":  "SOS",
        "totalCOP":  "574,200,000",
        "tipo":  "item",
        "total":  "130,500"
    },
    {
        "item":  "1.1.4",
        "descripcion":  "Panel solar 150W",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Alimentación autónoma",
        "unidad":  "UND",
        "vu":  "450",
        "sistema":  "SOS",
        "totalCOP":  "172,260,000",
        "tipo":  "item",
        "total":  "39,150"
    },
    {
        "item":  "1.1.5",
        "descripcion":  "Batería 12V 100Ah (×2)",
        "id":  "",
        "nivel":  "",
        "cantidad":  "174",
        "vuCOP":  "",
        "criterio":  "Respaldo energético",
        "unidad":  "UND",
        "vu":  "180",
        "sistema":  "SOS",
        "totalCOP":  "137,808,000",
        "tipo":  "item",
        "total":  "31,320"
    },
    {
        "item":  "1.1.6",
        "descripcion":  "Controlador solar MPPT",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Gestión energía",
        "unidad":  "UND",
        "vu":  "200",
        "sistema":  "SOS",
        "totalCOP":  "76,560,000",
        "tipo":  "item",
        "total":  "17,400"
    },
    {
        "item":  "1.1.7",
        "descripcion":  "Conversor FO/Ethernet",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Comunicación fibra",
        "unidad":  "UND",
        "vu":  "150",
        "sistema":  "SOS",
        "totalCOP":  "57,420,000",
        "tipo":  "item",
        "total":  "13,050"
    },
    {
        "item":  "1.1.8",
        "descripcion":  "Cableado control y energía",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Conexiones internas",
        "unidad":  "UND",
        "vu":  "120",
        "sistema":  "SOS",
        "totalCOP":  "45,936,000",
        "tipo":  "item",
        "total":  "10,440"
    },
    {
        "item":  "1.1.9",
        "descripcion":  "Baliza LED ámbar 12-24V",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Señalización visual",
        "unidad":  "UND",
        "vu":  "80",
        "sistema":  "SOS",
        "totalCOP":  "30,624,000",
        "tipo":  "item",
        "total":  "6,960"
    },
    {
        "item":  "1.1.10",
        "descripcion":  "Sirena piezo 110dB",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Señalización sonora",
        "unidad":  "UND",
        "vu":  "60",
        "sistema":  "SOS",
        "totalCOP":  "22,968,000",
        "tipo":  "item",
        "total":  "5,220"
    },
    {
        "item":  "1.1.11",
        "descripcion":  "Botón pulsador iluminado",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Activación emergencia",
        "unidad":  "UND",
        "vu":  "40",
        "sistema":  "SOS",
        "totalCOP":  "15,312,000",
        "tipo":  "item",
        "total":  "3,480"
    },
    {
        "item":  "1.1.12",
        "descripcion":  "DPS protección sobretensión",
        "id":  "",
        "nivel":  "",
        "cantidad":  "261",
        "vuCOP":  "",
        "criterio":  "Protección eléctrica",
        "unidad":  "UND",
        "vu":  "25",
        "sistema":  "SOS",
        "totalCOP":  "28,710,000",
        "tipo":  "item",
        "total":  "6,525"
    },
    {
        "item":  "1.1.13",
        "descripcion":  "Corona antiescalatoria",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Seguridad física",
        "unidad":  "UND",
        "vu":  "50",
        "sistema":  "SOS",
        "totalCOP":  "19,140,000",
        "tipo":  "item",
        "total":  "4,350"
    },
    {
        "item":  "1.1.14",
        "descripcion":  "Varilla puesta a tierra",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Protección eléctrica",
        "unidad":  "UND",
        "vu":  "15",
        "sistema":  "SOS",
        "totalCOP":  "5,742,000",
        "tipo":  "item",
        "total":  "1,305"
    },
    {
        "item":  "1.1.15",
        "descripcion":  "Cable UTP Cat6 ext 50m",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Conexión datos",
        "unidad":  "UND",
        "vu":  "30",
        "sistema":  "SOS",
        "totalCOP":  "11,484,000",
        "tipo":  "item",
        "total":  "2,610"
    },
    {
        "item":  "1.1.16",
        "descripcion":  "Ducto HDPE 2\\",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Protección cableado",
        "unidad":  "UND",
        "vu":  "20",
        "sistema":  "SOS",
        "totalCOP":  "7,656,000",
        "tipo":  "item",
        "total":  "1,740"
    },
    {
        "item":  "1.1.17",
        "descripcion":  "Instalación y comisionamiento",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Servicios especializados",
        "unidad":  "UND",
        "vu":  "1,200",
        "sistema":  "SOS",
        "totalCOP":  "459,360,000",
        "tipo":  "item",
        "total":  "104,400"
    },
    {
        "item":  "1.1.18",
        "descripcion":  "Pruebas FAT/SAT",
        "id":  "",
        "nivel":  "",
        "cantidad":  "87",
        "vuCOP":  "",
        "criterio":  "Validación funcional",
        "unidad":  "UND",
        "vu":  "200",
        "sistema":  "SOS",
        "totalCOP":  "76,560,000",
        "tipo":  "item",
        "total":  "17,400"
    },
    {
        "item":  "1.1.19",
        "descripcion":  "Documentación técnica",
        "id":  "",
        "nivel":  "",
        "cantidad":  "1",
        "vuCOP":  "",
        "criterio":  "Manuales y planos",
        "unidad":  "GLB",
        "vu":  "5,000",
        "sistema":  "SOS",
        "totalCOP":  "22,000,000",
        "tipo":  "item",
        "total":  "5,000"
    },
    {
        "item":  "1.1.20",
        "descripcion":  "Capacitación operadores",
        "id":  "",
        "nivel":  "",
        "cantidad":  "1",
        "vuCOP":  "",
        "criterio":  "Transferencia conocimiento",
        "unidad":  "GLB",
        "vu":  "3,000",
        "sistema":  "SOS",
        "totalCOP":  "13,200,000",
        "tipo":  "item",
        "total":  "3,000"
    },
    {
        "item":  "2",
        "descripcion":  "SISTEMA ETD/RADAR",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "ETD/RADAR",
        "totalCOP":  "",
        "tipo":  "capitulo",
        "total":  ""
    },
    {
        "item":  "2.1",
        "descripcion":  "SUMINISTROS ETD/RADAR",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "ETD/RADAR",
        "totalCOP":  "",
        "tipo":  "subcapitulo",
        "total":  ""
    },
    {
        "item":  "2.1.1",
        "descripcion":  "ETD con sensores piezoeléctricos",
        "id":  "",
        "nivel":  "",
        "cantidad":  "13",
        "vuCOP":  "88,000,000",
        "criterio":  "AT1 Cap. 3 - Criterio 15km",
        "unidad":  "UND",
        "vu":  "20,000",
        "sistema":  "ETD/RADAR",
        "totalCOP":  "1,144,000,000",
        "tipo":  "item",
        "total":  "260,000"
    },
    {
        "item":  "2.1.2",
        "descripcion":  "Radares sancionatorios ANPR",
        "id":  "",
        "nivel":  "",
        "cantidad":  "2",
        "vuCOP":  "246,571,600",
        "criterio":  "Control vehicular peajes",
        "unidad":  "UND",
        "vu":  "56,039",
        "sistema":  "ETD/RADAR",
        "totalCOP":  "493,143,200",
        "tipo":  "item",
        "total":  "112,078"
    },
    {
        "item":  "3",
        "descripcion":  "SISTEMA CCTV",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "CCTV",
        "totalCOP":  "",
        "tipo":  "capitulo",
        "total":  ""
    },
    {
        "item":  "3.1",
        "descripcion":  "SUMINISTROS CCTV",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "CCTV",
        "totalCOP":  "",
        "tipo":  "subcapitulo",
        "total":  ""
    },
    {
        "item":  "3.1.1",
        "descripcion":  "Cámaras IP PTZ con visión nocturna",
        "id":  "",
        "nivel":  "",
        "cantidad":  "30",
        "vuCOP":  "",
        "criterio":  "AT1 Cap. 3 - Solo en peajes",
        "unidad":  "UND",
        "vu":  "11,880",
        "sistema":  "CCTV",
        "totalCOP":  "1,568,133,600",
        "tipo":  "item",
        "total":  "356,394"
    },
    {
        "item":  "3.1.2",
        "descripcion":  "Sistema VMS y almacenamiento",
        "id":  "",
        "nivel":  "",
        "cantidad":  "1",
        "vuCOP":  "",
        "criterio":  "Gestión centralizada",
        "unidad":  "SISTEMA",
        "vu":  "50,000",
        "sistema":  "CCTV",
        "totalCOP":  "220,000,000",
        "tipo":  "item",
        "total":  "50,000"
    },
    {
        "item":  "4",
        "descripcion":  "SISTEMA PMV",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "PMV",
        "totalCOP":  "",
        "tipo":  "capitulo",
        "total":  ""
    },
    {
        "item":  "4.1",
        "descripcion":  "SUMINISTROS PMV",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "PMV",
        "totalCOP":  "",
        "tipo":  "subcapitulo",
        "total":  ""
    },
    {
        "item":  "4.1.1",
        "descripcion":  "Paneles LED tipo PASA-VÍAS",
        "id":  "",
        "nivel":  "",
        "cantidad":  "28",
        "vuCOP":  "",
        "criterio":  "AT1 Cap. 3 - Criterio 20km",
        "unidad":  "UND",
        "vu":  "100,586",
        "sistema":  "PMV",
        "totalCOP":  "12,392,195,200",
        "tipo":  "item",
        "total":  "2,816,408"
    },
    {
        "item":  "4.1.2",
        "descripcion":  "Sistema de gestión de contenido",
        "id":  "",
        "nivel":  "",
        "cantidad":  "1",
        "vuCOP":  "",
        "criterio":  "Control centralizado",
        "unidad":  "SISTEMA",
        "vu":  "25,000",
        "sistema":  "PMV",
        "totalCOP":  "110,000,000",
        "tipo":  "item",
        "total":  "25,000"
    },
    {
        "item":  "5",
        "descripcion":  "SISTEMA GÁLIBOS",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "GALIBOS",
        "totalCOP":  "",
        "tipo":  "capitulo",
        "total":  ""
    },
    {
        "item":  "5.1",
        "descripcion":  "SUMINISTROS GÁLIBOS",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "GALIBOS",
        "totalCOP":  "",
        "tipo":  "subcapitulo",
        "total":  ""
    },
    {
        "item":  "5.1.1",
        "descripcion":  "Gálibos de altura 4.5m",
        "id":  "",
        "nivel":  "",
        "cantidad":  "8",
        "vuCOP":  "",
        "criterio":  "Control altura vehicular",
        "unidad":  "UND",
        "vu":  "21,630",
        "sistema":  "GALIBOS",
        "totalCOP":  "761,389,200",
        "tipo":  "item",
        "total":  "173,043"
    },
    {
        "item":  "6",
        "descripcion":  "SISTEMA METEO",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "METEO",
        "totalCOP":  "",
        "tipo":  "capitulo",
        "total":  ""
    },
    {
        "item":  "6.1",
        "descripcion":  "SUMINISTROS METEO",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "METEO",
        "totalCOP":  "",
        "tipo":  "subcapitulo",
        "total":  ""
    },
    {
        "item":  "6.1.1",
        "descripcion":  "Estaciones Davis Vantage Pro2",
        "id":  "",
        "nivel":  "",
        "cantidad":  "2",
        "vuCOP":  "",
        "criterio":  "NTC 5660 + Supervisión CCO",
        "unidad":  "UND",
        "vu":  "3,386",
        "sistema":  "METEO",
        "totalCOP":  "29,796,800",
        "tipo":  "item",
        "total":  "6,772"
    },
    {
        "item":  "7",
        "descripcion":  "SISTEMA PEAJES",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "PEAJES",
        "totalCOP":  "",
        "tipo":  "capitulo",
        "total":  ""
    },
    {
        "item":  "7.1",
        "descripcion":  "SUMINISTROS PEAJES",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "PEAJES",
        "totalCOP":  "",
        "tipo":  "subcapitulo",
        "total":  ""
    },
    {
        "item":  "7.1.1",
        "descripcion":  "Sistemas de recaudo automático",
        "id":  "",
        "nivel":  "",
        "cantidad":  "2",
        "vuCOP":  "",
        "criterio":  "Recaudo vehicular",
        "unidad":  "UND",
        "vu":  "490,081",
        "sistema":  "PEAJES",
        "totalCOP":  "4,312,708,400",
        "tipo":  "item",
        "total":  "980,161"
    },
    {
        "item":  "8",
        "descripcion":  "SISTEMA CCO",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "CCO",
        "totalCOP":  "",
        "tipo":  "capitulo",
        "total":  ""
    },
    {
        "item":  "8.1",
        "descripcion":  "SUMINISTROS CCO",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "CCO",
        "totalCOP":  "",
        "tipo":  "subcapitulo",
        "total":  ""
    },
    {
        "item":  "8.1.1",
        "descripcion":  "Centro de Control completo",
        "id":  "",
        "nivel":  "",
        "cantidad":  "1",
        "vuCOP":  "",
        "criterio":  "Control centralizado",
        "unidad":  "UND",
        "vu":  "1,165,000",
        "sistema":  "CCO",
        "totalCOP":  "5,126,000,000",
        "tipo":  "item",
        "total":  "1,165,000"
    },
    {
        "item":  "9",
        "descripcion":  "SISTEMA WIM",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "WIM",
        "totalCOP":  "",
        "tipo":  "capitulo",
        "total":  ""
    },
    {
        "item":  "9.1",
        "descripcion":  "SUMINISTROS WIM",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "WIM",
        "totalCOP":  "",
        "tipo":  "subcapitulo",
        "total":  ""
    },
    {
        "item":  "9.1.1",
        "descripcion":  "Básculas dinámicas WIM (2 plataformas)",
        "id":  "",
        "nivel":  "",
        "cantidad":  "2",
        "vuCOP":  "",
        "criterio":  "Pesaje en movimiento",
        "unidad":  "UND",
        "vu":  "140,000",
        "sistema":  "WIM",
        "totalCOP":  "1,232,000,000",
        "tipo":  "item",
        "total":  "280,000"
    },
    {
        "item":  "9.1.2",
        "descripcion":  "Básculas estáticas 100t (2 plataformas)",
        "id":  "",
        "nivel":  "",
        "cantidad":  "2",
        "vuCOP":  "",
        "criterio":  "Pesaje estático verificación",
        "unidad":  "UND",
        "vu":  "95,000",
        "sistema":  "WIM",
        "totalCOP":  "836,000,000",
        "tipo":  "item",
        "total":  "190,000"
    },
    {
        "item":  "9.1.3",
        "descripcion":  "Sensores de ejes y loops inductivos",
        "id":  "",
        "nivel":  "",
        "cantidad":  "8",
        "vuCOP":  "",
        "criterio":  "Detección de ejes",
        "unidad":  "UND",
        "vu":  "8,500",
        "sistema":  "WIM",
        "totalCOP":  "299,200,000",
        "tipo":  "item",
        "total":  "68,000"
    },
    {
        "item":  "9.1.4",
        "descripcion":  "Sistema de control y gestión",
        "id":  "",
        "nivel":  "",
        "cantidad":  "1",
        "vuCOP":  "",
        "criterio":  "Gestión centralizada",
        "unidad":  "SISTEMA",
        "vu":  "13,425",
        "sistema":  "WIM",
        "totalCOP":  "59,070,000",
        "tipo":  "item",
        "total":  "13,425"
    },
    {
        "item":  "10",
        "descripcion":  "TELECOMUNICACIONES ITS",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "TELECOM",
        "totalCOP":  "",
        "tipo":  "capitulo",
        "total":  ""
    },
    {
        "item":  "10.1",
        "descripcion":  "SUMINISTROS TELECOM",
        "id":  "",
        "nivel":  "",
        "cantidad":  "",
        "vuCOP":  "",
        "criterio":  "",
        "unidad":  "",
        "vu":  "",
        "sistema":  "TELECOM",
        "totalCOP":  "",
        "tipo":  "subcapitulo",
        "total":  ""
    },
    {
        "item":  "10.1.1",
        "descripcion":  "Cable fibra óptica 48 hilos (322 km)",
        "id":  "",
        "nivel":  "",
        "cantidad":  "322",
        "vuCOP":  "",
        "criterio":  "Backbone comunicaciones",
        "unidad":  "KM",
        "vu":  "2,500",
        "sistema":  "TELECOM",
        "totalCOP":  "3,542,000,000",
        "tipo":  "item",
        "total":  "805,000"
    },
    {
        "item":  "10.1.2",
        "descripcion":  "Ductos HDPE 4\\",
        "id":  "",
        "nivel":  "",
        "cantidad":  "322",
        "vuCOP":  "",
        "criterio":  "Protección fibra",
        "unidad":  "KM",
        "vu":  "50",
        "sistema":  "TELECOM",
        "totalCOP":  "70,840,000",
        "tipo":  "item",
        "total":  "16,100"
    },
    {
        "item":  "10.1.3",
        "descripcion":  "Switches L3 Core (7 nodos)",
        "id":  "",
        "nivel":  "",
        "cantidad":  "7",
        "vuCOP":  "",
        "criterio":  "Nodos principales",
        "unidad":  "UND",
        "vu":  "15,000",
        "sistema":  "TELECOM",
        "totalCOP":  "462,000,000",
        "tipo":  "item",
        "total":  "105,000"
    },
    {
        "item":  "10.1.4",
        "descripcion":  "Switches L2 Acceso (150 gabinetes)",
        "id":  "",
        "nivel":  "",
        "cantidad":  "150",
        "vuCOP":  "",
        "criterio":  "Acceso equipos ITS",
        "unidad":  "UND",
        "vu":  "2,000",
        "sistema":  "TELECOM",
        "totalCOP":  "1,320,000,000",
        "tipo":  "item",
        "total":  "300,000"
    },
    {
        "item":  "10.1.5",
        "descripcion":  "Cajas empalme y fusiones",
        "id":  "",
        "nivel":  "",
        "cantidad":  "1",
        "vuCOP":  "",
        "criterio":  "Empalmes fibra",
        "unidad":  "GLB",
        "vu":  "200,251",
        "sistema":  "TELECOM",
        "totalCOP":  "881,104,400",
        "tipo":  "item",
        "total":  "200,251"
    }
]
};

// Funciones de ayuda para acceder a los datos
function obtenerItemsWBS() {
    return window.datos_wbs.items;
}

function obtenerItemsPorSistema(sistema) {
    return window.datos_wbs.items.filter(item => item.sistema === sistema);
}

function obtenerItemsPorNivel(nivel) {
    return window.datos_wbs.items.filter(item => item.nivel === nivel);
}

// Funcion para calcular totales por sistema
function calcularTotalesPorSistema() {
    const totales = {};
    window.datos_wbs.items.forEach(item => {
        if (item.nivel === 3 && item.sistema) {
            if (!totales[item.sistema]) {
                totales[item.sistema] = {
                    cantidad: 0,
                    costoTotalUSD: 0,
                    costoTotalCOP: 0,
                    items: 0
                };
            }
            
            const cantidad = parseFloat(item.cantidad?.replace(/,/g, '') || 0);
            const costoUSD = parseFloat(item.total?.replace(/,/g, '') || 0);
            const costoCOP = parseFloat(item.totalCOP?.replace(/,/g, '') || 0);
            
            totales[item.sistema].cantidad += cantidad;
            totales[item.sistema].costoTotalUSD += costoUSD;
            totales[item.sistema].costoTotalCOP += costoCOP;
            totales[item.sistema].items += 1;
        }
    });
    
    return totales;
}

console.log('Datos WBS TM01 cargados:', window.datos_wbs);
