// Datos WBS TM01 Troncal Magdalena
// Generado para Sistema de Validación ITS
// Fecha: 2025-10-23
// Total items: 24

window.wbsDataGlobal = window.datos_wbs = {
    "fecha_actualizacion": "2025-10-23",
    "total_capitulos": 6,
    "version": "1.0",
    "items": [
        // CAPÍTULO 1: SISTEMA SOS (POSTES DE AUXILIO)
        {
            "codigo": "1",
            "descripcion": "SISTEMA SOS (POSTES DE AUXILIO)",
            "capitulo": "1",
            "subcapitulo": "",
            "categoria": "SOS",
            "tipo": "capitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "1.1",
            "descripcion": "SUMINISTROS SOS",
            "capitulo": "1",
            "subcapitulo": "1.1",
            "categoria": "SOS",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "1.1.1",
            "descripcion": "Poste SOS con panel solar y batería",
            "capitulo": "1",
            "subcapitulo": "1.1",
            "categoria": "SOS",
            "tipo": "item",
            "cantidad": "88",
            "unidad": "UND",
            "vu_cop": 66000000,
            "total_cop": 5808000000,
            "modificable": true,
            "riesgos_asociados": ["R1", "R2"],
            "archivos_relacionados": ["AT1_Cap3.md", "Especificaciones_SOS.md"]
        },
        {
            "codigo": "1.1.2",
            "descripcion": "Botón de emergencia SOS",
            "capitulo": "1",
            "subcapitulo": "1.1",
            "categoria": "SOS",
            "tipo": "item",
            "cantidad": "88",
            "unidad": "UND",
            "vu_cop": 2200000,
            "total_cop": 193600000,
            "modificable": true,
            "riesgos_asociados": ["R1"],
            "archivos_relacionados": ["AT1_Cap3.md"]
        },
        {
            "codigo": "1.1.3",
            "descripcion": "Panel solar 100W",
            "capitulo": "1",
            "subcapitulo": "1.1",
            "categoria": "SOS",
            "tipo": "item",
            "cantidad": "88",
            "unidad": "UND",
            "vu_cop": 8800000,
            "total_cop": 774400000,
            "modificable": true,
            "riesgos_asociados": ["R2"],
            "archivos_relacionados": ["Especificaciones_SOS.md"]
        },
        {
            "codigo": "1.1.4",
            "descripcion": "Batería gel 12V 100Ah",
            "capitulo": "1",
            "subcapitulo": "1.1",
            "categoria": "SOS",
            "tipo": "item",
            "cantidad": "88",
            "unidad": "UND",
            "vu_cop": 6600000,
            "total_cop": 580800000,
            "modificable": true,
            "riesgos_asociados": ["R2"],
            "archivos_relacionados": ["Especificaciones_SOS.md"]
        },
        {
            "codigo": "1.2",
            "descripcion": "OBRA CIVIL SOS",
            "capitulo": "1",
            "subcapitulo": "1.2",
            "categoria": "SOS",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "1.2.1",
            "descripcion": "Cimentación poste SOS",
            "capitulo": "1",
            "subcapitulo": "1.2",
            "categoria": "SOS",
            "tipo": "item",
            "cantidad": "88",
            "unidad": "UND",
            "vu_cop": 8800000,
            "total_cop": 774400000,
            "modificable": true,
            "riesgos_asociados": ["R3"],
            "archivos_relacionados": ["Planos_Obra_Civil.md"]
        },
        {
            "codigo": "1.2.2",
            "descripcion": "Instalación poste y equipos",
            "capitulo": "1",
            "subcapitulo": "1.2",
            "categoria": "SOS",
            "tipo": "item",
            "cantidad": "88",
            "unidad": "UND",
            "vu_cop": 4400000,
            "total_cop": 387200000,
            "modificable": true,
            "riesgos_asociados": ["R3", "R4"],
            "archivos_relacionados": ["Manual_Instalacion.md"]
        },

        // CAPÍTULO 2: SISTEMA ETD/RADAR
        {
            "codigo": "2",
            "descripcion": "SISTEMA ETD/RADAR",
            "capitulo": "2",
            "subcapitulo": "",
            "categoria": "ETD/RADAR",
            "tipo": "capitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "2.1",
            "descripcion": "SUMINISTROS ETD",
            "capitulo": "2",
            "subcapitulo": "2.1",
            "categoria": "ETD/RADAR",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "2.1.1",
            "descripcion": "Estación de Tratamiento de Datos (ETD)",
            "capitulo": "2",
            "subcapitulo": "2.1",
            "categoria": "ETD/RADAR",
            "tipo": "item",
            "cantidad": "14",
            "unidad": "UND",
            "vu_cop": 880000000,
            "total_cop": 12320000000,
            "modificable": true,
            "riesgos_asociados": ["R5", "R6"],
            "archivos_relacionados": ["AT1_Cap3.md", "Especificaciones_ETD.md"]
        },
        {
            "codigo": "2.1.2",
            "descripcion": "Radares de velocidad",
            "capitulo": "2",
            "subcapitulo": "2.1",
            "categoria": "ETD/RADAR",
            "tipo": "item",
            "cantidad": "2",
            "unidad": "UND",
            "vu_cop": 880000000,
            "total_cop": 1760000000,
            "modificable": true,
            "riesgos_asociados": ["R5"],
            "archivos_relacionados": ["Especificaciones_ETD.md"]
        },
        {
            "codigo": "2.1.3",
            "descripcion": "Cámaras de reconocimiento",
            "capitulo": "2",
            "subcapitulo": "2.1",
            "categoria": "ETD/RADAR",
            "tipo": "item",
            "cantidad": "14",
            "unidad": "UND",
            "vu_cop": 66000000,
            "total_cop": 924000000,
            "modificable": true,
            "riesgos_asociados": ["R6"],
            "archivos_relacionados": ["Especificaciones_ETD.md"]
        },
        {
            "codigo": "2.2",
            "descripcion": "OBRA CIVIL ETD/RADAR",
            "capitulo": "2",
            "subcapitulo": "2.2",
            "categoria": "ETD/RADAR",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "2.2.1",
            "descripcion": "Cimentación equipos ETD",
            "capitulo": "2",
            "subcapitulo": "2.2",
            "categoria": "ETD/RADAR",
            "tipo": "item",
            "cantidad": "16",
            "unidad": "UND",
            "vu_cop": 13200000,
            "total_cop": 211200000,
            "modificable": true,
            "riesgos_asociados": ["R3"],
            "archivos_relacionados": ["Planos_Obra_Civil.md"]
        },

        // CAPÍTULO 3: SISTEMA CCTV
        {
            "codigo": "3",
            "descripcion": "SISTEMA CCTV",
            "capitulo": "3",
            "subcapitulo": "",
            "categoria": "CCTV",
            "tipo": "capitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "3.1",
            "descripcion": "SUMINISTROS CCTV",
            "capitulo": "3",
            "subcapitulo": "3.1",
            "categoria": "CCTV",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "3.1.1",
            "descripcion": "Cámaras PAN",
            "capitulo": "3",
            "subcapitulo": "3.1",
            "categoria": "CCTV",
            "tipo": "item",
            "cantidad": "30",
            "unidad": "UND",
            "vu_cop": 132000000,
            "total_cop": 3960000000,
            "modificable": true,
            "riesgos_asociados": ["R7"],
            "archivos_relacionados": ["AT1_Cap3.md", "Especificaciones_CCTV.md"]
        },
        {
            "codigo": "3.1.2",
            "descripcion": "Cámaras fijas",
            "capitulo": "3",
            "subcapitulo": "3.1",
            "categoria": "CCTV",
            "tipo": "item",
            "cantidad": "15",
            "unidad": "UND",
            "vu_cop": 132000000,
            "total_cop": 1980000000,
            "modificable": true,
            "riesgos_asociados": ["R7"],
            "archivos_relacionados": ["Especificaciones_CCTV.md"]
        },
        {
            "codigo": "3.1.3",
            "descripcion": "Servidor de video",
            "capitulo": "3",
            "subcapitulo": "3.1",
            "categoria": "CCTV",
            "tipo": "item",
            "cantidad": "1",
            "unidad": "UND",
            "vu_cop": 220000000,
            "total_cop": 220000000,
            "modificable": true,
            "riesgos_asociados": ["R8"],
            "archivos_relacionados": ["Especificaciones_CCTV.md"]
        },
        {
            "codigo": "3.2",
            "descripcion": "OBRA CIVIL CCTV",
            "capitulo": "3",
            "subcapitulo": "3.2",
            "categoria": "CCTV",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "3.2.1",
            "descripcion": "Instalación cámaras",
            "capitulo": "3",
            "subcapitulo": "3.2",
            "categoria": "CCTV",
            "tipo": "item",
            "cantidad": "30",
            "unidad": "UND",
            "vu_cop": 4400000,
            "total_cop": 132000000,
            "modificable": true,
            "riesgos_asociados": ["R3", "R4"],
            "archivos_relacionados": ["Manual_Instalacion.md"]
        },

        // CAPÍTULO 4: SISTEMA PMV
        {
            "codigo": "4",
            "descripcion": "SISTEMA PMV",
            "capitulo": "4",
            "subcapitulo": "",
            "categoria": "PMV",
            "tipo": "capitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "4.1",
            "descripcion": "SUMINISTROS PMV",
            "capitulo": "4",
            "subcapitulo": "4.1",
            "categoria": "PMV",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "4.1.1",
            "descripcion": "Paneles de mensaje variable",
            "capitulo": "4",
            "subcapitulo": "4.1",
            "categoria": "PMV",
            "tipo": "item",
            "cantidad": "12",
            "unidad": "UND",
            "vu_cop": 220000000,
            "total_cop": 2640000000,
            "modificable": true,
            "riesgos_asociados": ["R9"],
            "archivos_relacionados": ["AT1_Cap3.md", "Especificaciones_PMV.md"]
        },
        {
            "codigo": "4.1.2",
            "descripcion": "Controladores PMV",
            "capitulo": "4",
            "subcapitulo": "4.1",
            "categoria": "PMV",
            "tipo": "item",
            "cantidad": "12",
            "unidad": "UND",
            "vu_cop": 66000000,
            "total_cop": 792000000,
            "modificable": true,
            "riesgos_asociados": ["R9"],
            "archivos_relacionados": ["Especificaciones_PMV.md"]
        },
        {
            "codigo": "4.1.3",
            "descripcion": "Módulos solares",
            "capitulo": "4",
            "subcapitulo": "4.1",
            "categoria": "PMV",
            "tipo": "item",
            "cantidad": "12",
            "unidad": "UND",
            "vu_cop": 35200000,
            "total_cop": 422400000,
            "modificable": true,
            "riesgos_asociados": ["R2"],
            "archivos_relacionados": ["Especificaciones_PMV.md"]
        },
        {
            "codigo": "4.2",
            "descripcion": "OBRA CIVIL PMV",
            "capitulo": "4",
            "subcapitulo": "4.2",
            "categoria": "PMV",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "4.2.1",
            "descripcion": "Instalación PMV",
            "capitulo": "4",
            "subcapitulo": "4.2",
            "categoria": "PMV",
            "tipo": "item",
            "cantidad": "12",
            "unidad": "UND",
            "vu_cop": 8800000,
            "total_cop": 105600000,
            "modificable": true,
            "riesgos_asociados": ["R3", "R4"],
            "archivos_relacionados": ["Manual_Instalacion.md"]
        },

        // CAPÍTULO 5: SISTEMA METEO
        {
            "codigo": "5",
            "descripcion": "SISTEMA METEO",
            "capitulo": "5",
            "subcapitulo": "",
            "categoria": "METEO",
            "tipo": "capitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "5.1",
            "descripcion": "SUMINISTROS METEO",
            "capitulo": "5",
            "subcapitulo": "5.1",
            "categoria": "METEO",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "5.1.1",
            "descripcion": "Estaciones meteorológicas Davis Pro2",
            "capitulo": "5",
            "subcapitulo": "5.1",
            "categoria": "METEO",
            "tipo": "item",
            "cantidad": "3",
            "unidad": "UND",
            "vu_cop": 220000000,
            "total_cop": 660000000,
            "modificable": true,
            "riesgos_asociados": ["R10"],
            "archivos_relacionados": ["AT1_Cap3.md", "Especificaciones_METEO.md"]
        },
        {
            "codigo": "5.1.2",
            "descripcion": "Sensores meteorológicos",
            "capitulo": "5",
            "subcapitulo": "5.1",
            "categoria": "METEO",
            "tipo": "item",
            "cantidad": "3",
            "unidad": "UND",
            "vu_cop": 22000000,
            "total_cop": 66000000,
            "modificable": true,
            "riesgos_asociados": ["R10"],
            "archivos_relacionados": ["Especificaciones_METEO.md"]
        },
        {
            "codigo": "5.2",
            "descripcion": "OBRA CIVIL METEO",
            "capitulo": "5",
            "subcapitulo": "5.2",
            "categoria": "METEO",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "5.2.1",
            "descripcion": "Instalación estaciones meteo",
            "capitulo": "5",
            "subcapitulo": "5.2",
            "categoria": "METEO",
            "tipo": "item",
            "cantidad": "3",
            "unidad": "UND",
            "vu_cop": 4400000,
            "total_cop": 13200000,
            "modificable": true,
            "riesgos_asociados": ["R3"],
            "archivos_relacionados": ["Manual_Instalacion.md"]
        },

        // CAPÍTULO 6: SISTEMA WIM
        {
            "codigo": "6",
            "descripcion": "SISTEMA WIM",
            "capitulo": "6",
            "subcapitulo": "",
            "categoria": "WIM",
            "tipo": "capitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "6.1",
            "descripcion": "SUMINISTROS WIM",
            "capitulo": "6",
            "subcapitulo": "6.1",
            "categoria": "WIM",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "6.1.1",
            "descripcion": "Sistema WIM dinámico",
            "capitulo": "6",
            "subcapitulo": "6.1",
            "categoria": "WIM",
            "tipo": "item",
            "cantidad": "1",
            "unidad": "UND",
            "vu_cop": 660000000,
            "total_cop": 660000000,
            "modificable": true,
            "riesgos_asociados": ["R11"],
            "archivos_relacionados": ["AT1_Cap3.md", "Especificaciones_WIM.md"]
        },
        {
            "codigo": "6.1.2",
            "descripcion": "Báscula estática",
            "capitulo": "6",
            "subcapitulo": "6.1",
            "categoria": "WIM",
            "tipo": "item",
            "cantidad": "1",
            "unidad": "UND",
            "vu_cop": 440000000,
            "total_cop": 440000000,
            "modificable": true,
            "riesgos_asociados": ["R11"],
            "archivos_relacionados": ["Especificaciones_WIM.md"]
        },
        {
            "codigo": "6.1.3",
            "descripcion": "Sensores de pesaje dinámico",
            "capitulo": "6",
            "subcapitulo": "6.1",
            "categoria": "WIM",
            "tipo": "item",
            "cantidad": "4",
            "unidad": "UND",
            "vu_cop": 66000000,
            "total_cop": 264000000,
            "modificable": true,
            "riesgos_asociados": ["R11"],
            "archivos_relacionados": ["Especificaciones_WIM.md"]
        },
        {
            "codigo": "6.1.4",
            "descripcion": "Sistema de control integrado",
            "capitulo": "6",
            "subcapitulo": "6.1",
            "categoria": "WIM",
            "tipo": "item",
            "cantidad": "1",
            "unidad": "UND",
            "vu_cop": 220000000,
            "total_cop": 220000000,
            "modificable": true,
            "riesgos_asociados": ["R8"],
            "archivos_relacionados": ["Especificaciones_WIM.md"]
        },
        {
            "codigo": "6.2",
            "descripcion": "OBRA CIVIL WIM",
            "capitulo": "6",
            "subcapitulo": "6.2",
            "categoria": "WIM",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "6.2.1",
            "descripcion": "Cimentaciones WIM dinámico",
            "capitulo": "6",
            "subcapitulo": "6.2",
            "categoria": "WIM",
            "tipo": "item",
            "cantidad": "1",
            "unidad": "UND",
            "vu_cop": 35200000,
            "total_cop": 35200000,
            "modificable": true,
            "riesgos_asociados": ["R3"],
            "archivos_relacionados": ["Planos_Obra_Civil.md"]
        },
        {
            "codigo": "6.2.2",
            "descripcion": "Cimentaciones báscula estática",
            "capitulo": "6",
            "subcapitulo": "6.2",
            "categoria": "WIM",
            "tipo": "item",
            "cantidad": "1",
            "unidad": "UND",
            "vu_cop": 22000000,
            "total_cop": 22000000,
            "modificable": true,
            "riesgos_asociados": ["R3"],
            "archivos_relacionados": ["Planos_Obra_Civil.md"]
        },
        {
            "codigo": "6.3",
            "descripcion": "SERVICIOS WIM",
            "capitulo": "6",
            "subcapitulo": "6.3",
            "categoria": "WIM",
            "tipo": "subcapitulo",
            "cantidad": "",
            "unidad": "",
            "vu_cop": 0,
            "total_cop": 0,
            "modificable": false,
            "riesgos_asociados": [],
            "archivos_relacionados": []
        },
        {
            "codigo": "6.3.1",
            "descripcion": "Instalación sistema completo",
            "capitulo": "6",
            "subcapitulo": "6.3",
            "categoria": "WIM",
            "tipo": "item",
            "cantidad": "1",
            "unidad": "UND",
            "vu_cop": 22000000,
            "total_cop": 22000000,
            "modificable": true,
            "riesgos_asociados": ["R3", "R4"],
            "archivos_relacionados": ["Manual_Instalacion.md"]
        }
    ]
};
